version: '3.8'

services:
  frontend:
    build: ./heard-interview-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./heard-interview-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./heard-interview-backend
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./heard-interview-backend:/app
